/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sebas
 */
public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Administrador
     */
    public Administrador() {
        
        initComponents();
        setSize(800, 500);
        setTitle("Módulo de Administrador");
        setResizable(false);
        setLocationRelativeTo(null);
        
        
        
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_admin = new javax.swing.JTabbedPane();
        pestaña_investigadores = new javax.swing.JPanel();
        crear_btn = new javax.swing.JButton();
        cargar_btn = new javax.swing.JButton();
        actualizar_btn = new javax.swing.JButton();
        eliminar_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_investigadores = new javax.swing.JTable();
        pestaña_muestras = new javax.swing.JPanel();
        pestaña_asignacion = new javax.swing.JPanel();
        pestaña_patrones = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        crear_btn.setText("CREAR");
        crear_btn.setPreferredSize(new java.awt.Dimension(72, 50));
        crear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear_btnActionPerformed(evt);
            }
        });

        cargar_btn.setText("CARGAR");

        actualizar_btn.setText("ACTUALIZAR");

        eliminar_btn.setText("ELIMINAR");

        tabla_investigadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Género", "Experimentos"
            }
        ));
        jScrollPane1.setViewportView(tabla_investigadores);

        javax.swing.GroupLayout pestaña_investigadoresLayout = new javax.swing.GroupLayout(pestaña_investigadores);
        pestaña_investigadores.setLayout(pestaña_investigadoresLayout);
        pestaña_investigadoresLayout.setHorizontalGroup(
            pestaña_investigadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pestaña_investigadoresLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(pestaña_investigadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pestaña_investigadoresLayout.createSequentialGroup()
                        .addComponent(actualizar_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eliminar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pestaña_investigadoresLayout.createSequentialGroup()
                        .addComponent(crear_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(cargar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        pestaña_investigadoresLayout.setVerticalGroup(
            pestaña_investigadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestaña_investigadoresLayout.createSequentialGroup()
                .addGroup(pestaña_investigadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pestaña_investigadoresLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(pestaña_investigadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cargar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(crear_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(pestaña_investigadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eliminar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(actualizar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pestaña_investigadoresLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        panel_admin.addTab("Investigadores", pestaña_investigadores);

        javax.swing.GroupLayout pestaña_muestrasLayout = new javax.swing.GroupLayout(pestaña_muestras);
        pestaña_muestras.setLayout(pestaña_muestrasLayout);
        pestaña_muestrasLayout.setHorizontalGroup(
            pestaña_muestrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        pestaña_muestrasLayout.setVerticalGroup(
            pestaña_muestrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        panel_admin.addTab("Muestras", pestaña_muestras);

        javax.swing.GroupLayout pestaña_asignacionLayout = new javax.swing.GroupLayout(pestaña_asignacion);
        pestaña_asignacion.setLayout(pestaña_asignacionLayout);
        pestaña_asignacionLayout.setHorizontalGroup(
            pestaña_asignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        pestaña_asignacionLayout.setVerticalGroup(
            pestaña_asignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        panel_admin.addTab("Asignación de experimentos", pestaña_asignacion);

        javax.swing.GroupLayout pestaña_patronesLayout = new javax.swing.GroupLayout(pestaña_patrones);
        pestaña_patrones.setLayout(pestaña_patronesLayout);
        pestaña_patronesLayout.setHorizontalGroup(
            pestaña_patronesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        pestaña_patronesLayout.setVerticalGroup(
            pestaña_patronesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        panel_admin.addTab("Patrones", pestaña_patrones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_admin)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_admin)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crear_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar_btn;
    private javax.swing.JButton cargar_btn;
    private javax.swing.JButton crear_btn;
    private javax.swing.JButton eliminar_btn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane panel_admin;
    private javax.swing.JPanel pestaña_asignacion;
    private javax.swing.JPanel pestaña_investigadores;
    private javax.swing.JPanel pestaña_muestras;
    private javax.swing.JPanel pestaña_patrones;
    private javax.swing.JTable tabla_investigadores;
    // End of variables declaration//GEN-END:variables
}
