package interfaces;

//Se importan las bibliotecas de objeto investigador y para escribir los investigadores en el arraylist
import clases.Escribir_investigador;
import clases.Investigador;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import clases.RenderTabla;
import clases.Cargar_csv;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author sebas
 */
public class Administrador extends javax.swing.JFrame {

    //Se crea un dtm estático para agregar y actualizar datos de la tabla
    public static DefaultTableModel dtm1 = new DefaultTableModel();
    public static DefaultTableModel dtm_muestras;

    //Creación del botón VER de la tabla de muestras
    JButton ver = new JButton("VER");

    //Creación del constructor Administrador
    public Administrador() {

        initComponents();
        setSize(800, 500);
        setTitle("Módulo de Administrador");
        setResizable(false);
        setLocationRelativeTo(null);

        //Encabezados de las columnas de la tabla Investigadores
        String id[] = {"Código", "Nombre", "Genero", "Experimentos"};
        dtm1.setColumnIdentifiers(id); //Se agrega el vector id al encabezado de la tabla como títulos
        tabla_investigadores.setModel(dtm1); //Se asigna el dtm1 a la tabla_investigadores

        //Se crea la tabla que contiene las muestras
        tabla_muestras();

        //Se lee el arraylist y se agregan los elementos al JTable, si no hay elementos no se realiza ninguna acción
        if (Escribir_investigador.investigadores != null || Escribir_investigador.investigadores.size() != 0) {
            for (Investigador investigador_temp : Escribir_investigador.investigadores) {
                dtm1.addRow(new Object[]{investigador_temp.getCodigo(), investigador_temp.getNombre(), investigador_temp.getGenero(), investigador_temp.getNumExperimentos()}); //Se agrega el elemento a la tabla de Investigadores
                combo_investigador.addItem(investigador_temp.getNombre()); //Se agrega el elemento al JComboBox que está en la pestaña de Asignar Muestra
            }
        }

    }

    //Función para crear la tabla que contiene las muestras, especial porque se crea un botón en la última columna.
    public void tabla_muestras() {
        tabla_muestras.setDefaultRenderer(Object.class, new RenderTabla());
        dtm_muestras = new DefaultTableModel();
        String[] id = {"Código", "Descripción", "Estado", "Acciones"};
        dtm_muestras.setColumnIdentifiers(id); //Se agrega el vector id al encabezado de la tabla de muestras como títulos
        tabla_muestras.setModel(dtm_muestras); //A la tabla muestras se le asigna el modelo que se definió arriba
        tabla_muestras.setRowHeight(30); //Se ajusta el alto de la fila
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_admin = new javax.swing.JTabbedPane();
        pestaña_investigadores = new javax.swing.JPanel();
        crear_btn = new javax.swing.JButton();
        cargar_btn = new javax.swing.JButton();
        actualizar_btn = new javax.swing.JButton();
        eliminar_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_investigadores = new javax.swing.JTable();
        pestaña_muestras = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_muestras = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pestaña_asignacion = new javax.swing.JPanel();
        label_investigador = new javax.swing.JLabel();
        label_muestra = new javax.swing.JLabel();
        combo_investigador = new javax.swing.JComboBox<>();
        combo_muestra = new javax.swing.JComboBox<>();
        asignar_btn = new javax.swing.JButton();
        pestaña_patrones = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        crear_btn.setText("CREAR");
        crear_btn.setPreferredSize(new java.awt.Dimension(72, 50));
        crear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear_btnActionPerformed(evt);
            }
        });

        cargar_btn.setText("CARGAR");
        cargar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargar_btnActionPerformed(evt);
            }
        });

        actualizar_btn.setText("ACTUALIZAR");
        actualizar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizar_btnActionPerformed(evt);
            }
        });

        eliminar_btn.setText("ELIMINAR");
        eliminar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_btnActionPerformed(evt);
            }
        });

        tabla_investigadores = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        tabla_investigadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Género", "Experimentos"
            }
        ));
        jScrollPane1.setViewportView(tabla_investigadores);

        javax.swing.GroupLayout pestaña_investigadoresLayout = new javax.swing.GroupLayout(pestaña_investigadores);
        pestaña_investigadores.setLayout(pestaña_investigadoresLayout);
        pestaña_investigadoresLayout.setHorizontalGroup(
            pestaña_investigadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pestaña_investigadoresLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(pestaña_investigadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pestaña_investigadoresLayout.createSequentialGroup()
                        .addComponent(actualizar_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eliminar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pestaña_investigadoresLayout.createSequentialGroup()
                        .addComponent(crear_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(cargar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        pestaña_investigadoresLayout.setVerticalGroup(
            pestaña_investigadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestaña_investigadoresLayout.createSequentialGroup()
                .addGroup(pestaña_investigadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pestaña_investigadoresLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(pestaña_investigadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cargar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(crear_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(pestaña_investigadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eliminar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(actualizar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pestaña_investigadoresLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        panel_admin.addTab("Investigadores", pestaña_investigadores);

        tabla_muestras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabla_muestras);

        jButton1.setText("CREAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CARGAR");

        javax.swing.GroupLayout pestaña_muestrasLayout = new javax.swing.GroupLayout(pestaña_muestras);
        pestaña_muestras.setLayout(pestaña_muestrasLayout);
        pestaña_muestrasLayout.setHorizontalGroup(
            pestaña_muestrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestaña_muestrasLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addGroup(pestaña_muestrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        pestaña_muestrasLayout.setVerticalGroup(
            pestaña_muestrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestaña_muestrasLayout.createSequentialGroup()
                .addGroup(pestaña_muestrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pestaña_muestrasLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pestaña_muestrasLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        panel_admin.addTab("Muestras", pestaña_muestras);

        label_investigador.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        label_investigador.setText("Investigador:");

        label_muestra.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        label_muestra.setText("Muestra:");

        combo_investigador.setModel(new javax.swing.DefaultComboBoxModel<>());
        combo_investigador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_investigadorActionPerformed(evt);
            }
        });

        combo_muestra.setModel(new javax.swing.DefaultComboBoxModel<>());

        asignar_btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        asignar_btn.setText("ASIGNAR");
        asignar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignar_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pestaña_asignacionLayout = new javax.swing.GroupLayout(pestaña_asignacion);
        pestaña_asignacion.setLayout(pestaña_asignacionLayout);
        pestaña_asignacionLayout.setHorizontalGroup(
            pestaña_asignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestaña_asignacionLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addGroup(pestaña_asignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_investigador)
                    .addComponent(label_muestra))
                .addGap(56, 56, 56)
                .addGroup(pestaña_asignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combo_muestra, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_investigador, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(128, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pestaña_asignacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(asignar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(322, 322, 322))
        );
        pestaña_asignacionLayout.setVerticalGroup(
            pestaña_asignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestaña_asignacionLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(pestaña_asignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_investigador, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_investigador))
                .addGap(54, 54, 54)
                .addGroup(pestaña_asignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_muestra)
                    .addComponent(combo_muestra, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addComponent(asignar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );

        panel_admin.addTab("Asignación de experimentos", pestaña_asignacion);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout pestaña_patronesLayout = new javax.swing.GroupLayout(pestaña_patrones);
        pestaña_patrones.setLayout(pestaña_patronesLayout);
        pestaña_patronesLayout.setHorizontalGroup(
            pestaña_patronesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestaña_patronesLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(329, Short.MAX_VALUE))
        );
        pestaña_patronesLayout.setVerticalGroup(
            pestaña_patronesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestaña_patronesLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        panel_admin.addTab("Patrones", pestaña_patrones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_admin)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_admin, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Método que captura el evento del botón crear
    private void crear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear_btnActionPerformed
        new Crear_Investigador().setVisible(true);
    }//GEN-LAST:event_crear_btnActionPerformed

    //Método que captura el evento del botón actualizar
    private void actualizar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizar_btnActionPerformed
        new Actualizar_Investigador().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_actualizar_btnActionPerformed

    //Método que captura el evento del botón eliminar
    private void eliminar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_btnActionPerformed
        new Eliminar_Investigador().setVisible(true);
    }//GEN-LAST:event_eliminar_btnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Crear_muestra().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void combo_investigadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_investigadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_investigadorActionPerformed

    //Método para capturar el evento del botón asignar perteneciente al apartado: Asignación de experimentos.
    private void asignar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignar_btnActionPerformed
        
        //Strings auxiliares
        String investigador;
        String muestra;

        //Si alguno de los JComboBox no fue seleccionado, se despliega un mensaje de error
        if (combo_investigador.getSelectedItem() == null || combo_muestra.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Error en la asignación", "Error", JOptionPane.ERROR_MESSAGE);
        }
        //Si ambos JComboBox contienen información, se asigna la muestra al investigador
        else {
            investigador = combo_investigador.getSelectedItem().toString();
            muestra = combo_muestra.getSelectedItem().toString();
        }


    }//GEN-LAST:event_asignar_btnActionPerformed

    //Método que captura el evento del botón Cargar del apartado de: Investigadores
    private void cargar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargar_btnActionPerformed
        //Se crea un objeto de tipo Cargar_csv para utilizar los métodos para leer archivos
        Cargar_csv cargar = new Cargar_csv();
        if (cargar.cargarCSV() == 1) { //Si se cumple esta condición, el usuario ingresó sí seleccionó un archivo
            try {
                cargar.cargarAlArray(cargar.ruta); //Se utiliza el método para cargar los investigadores del csv al array y luego grabarlos en el archivo binario
            } catch (IOException ex) {
                Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_cargar_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar_btn;
    private javax.swing.JButton asignar_btn;
    private javax.swing.JButton cargar_btn;
    public static javax.swing.JComboBox<String> combo_investigador;
    public static javax.swing.JComboBox<String> combo_muestra;
    private javax.swing.JButton crear_btn;
    private javax.swing.JButton eliminar_btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel label_investigador;
    private javax.swing.JLabel label_muestra;
    private javax.swing.JTabbedPane panel_admin;
    private javax.swing.JPanel pestaña_asignacion;
    private javax.swing.JPanel pestaña_investigadores;
    private javax.swing.JPanel pestaña_muestras;
    private javax.swing.JPanel pestaña_patrones;
    private javax.swing.JTable tabla_investigadores;
    private javax.swing.JTable tabla_muestras;
    // End of variables declaration//GEN-END:variables
}
