/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

//Importando librerías 
import clases.Actualizar_Tabla;
import clases.Escribir_InvestigadorBinario;
import clases.Escribir_investigador;
import clases.Investigador;
import javax.swing.JOptionPane;

/**
 *
 * @author sebas
 */
public class Crear_Investigador extends javax.swing.JFrame {

    /**
     * Creates new form NuevoInvestigador
     */
    public Crear_Investigador() {
        initComponents();
        setTitle("Crear Investigador");
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_codigo = new javax.swing.JLabel();
        label_nombre = new javax.swing.JLabel();
        label_genero = new javax.swing.JLabel();
        label_contrasenia = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        field_codigo = new javax.swing.JTextField();
        field_nombre = new javax.swing.JTextField();
        field_genero = new javax.swing.JTextField();
        field_contra = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        label_codigo.setText("Código: ");

        label_nombre.setText("Nombre:");

        label_genero.setText("Género (M/F):");

        label_contrasenia.setText("Contraseña:");

        jButton1.setText("CREAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        field_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_codigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_genero)
                                .addGap(40, 40, 40)
                                .addComponent(field_genero, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_codigo)
                                    .addComponent(label_nombre)
                                    .addComponent(label_contrasenia))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(field_nombre)
                                    .addComponent(field_contra)
                                    .addComponent(field_codigo)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jButton1)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_codigo)
                    .addComponent(field_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nombre)
                    .addComponent(field_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_genero)
                    .addComponent(field_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_contrasenia)
                    .addComponent(field_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String codigo, nombre, contrasenia;
        char genero = '\u0000';
        Investigador investigador = new Investigador();
        
        codigo = field_codigo.getText();
        nombre = field_nombre.getText();
        contrasenia = field_contra.getText();
        
        if(!field_genero.getText().equals("")){
            genero = field_genero.getText().charAt(0);
            genero = Character.toUpperCase(genero);
        }
        
        if(codigo.equals("") || nombre.equals("") || contrasenia.equals("") || genero == '\u0000'){
            JOptionPane.showMessageDialog(null,"Ingrese todos los campos");
        }
        else if(genero != 'M' && genero != 'F' ){
            JOptionPane.showMessageDialog(null, "Ingrese un género válido");
        }
        else if(!Escribir_investigador.investigadores.isEmpty() && Escribir_investigador.comparar_codigo(codigo) == true){
            JOptionPane.showMessageDialog(null,"El código que ingresó ya existe, ingrese uno válido");
        }
        else{
            
            investigador.setCodigo(codigo);
            investigador.setNombre(nombre);
            investigador.setGenero(genero);
            investigador.setContrasenia(contrasenia);
            investigador.setNumExperimentos(0);
            investigador.setMuestra_asignada(null);
            
            Escribir_investigador.investigadores.add(investigador);
            Escribir_InvestigadorBinario.escribir_investigadorbin();
            
            Actualizar_Tabla.nuevo_elemento(Administrador.dtm1, Escribir_investigador.investigadores);
            
            JOptionPane.showMessageDialog(null,"Investigador ingresado correctamente");
            
            dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void field_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_codigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crear_Investigador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crear_Investigador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crear_Investigador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crear_Investigador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crear_Investigador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField field_codigo;
    private javax.swing.JTextField field_contra;
    private javax.swing.JTextField field_genero;
    private javax.swing.JTextField field_nombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel label_codigo;
    private javax.swing.JLabel label_contrasenia;
    private javax.swing.JLabel label_genero;
    private javax.swing.JLabel label_nombre;
    // End of variables declaration//GEN-END:variables
}
